name: Build/Test

on: [push, pull_request]

jobs:
  test-unit:
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - ubuntu-16.04
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
      - name: Lint
        run: npm run lint
      - name: Typescript Build
        run: npm run build
      - name: NCC Package
        run: npm run package
      - name: Test
        run: npm run test
      - name: Coverage
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v1
  test-system:
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - ubuntu-16.04
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Action
        id: repolinter
        uses: ./
        with:
          config_file: ./.github/workflows/repolinter-test.json
      - name: Verify Outputs
        env:
          DID_ERROR: ${{ steps.repolinter.outputs.errored }}
          DID_PASS: ${{ steps.repolinter.outputs.passed }}
        shell: bash
        run: '[ "$DID_ERROR" = "false" ] && [ "$DID_PASS" = "true" ]'